import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Zap, TrendingUp, AlertTriangle, Lightbulb, ArrowRight, Loader2, X, CheckCircle, Download, RefreshCcw } from 'lucide-react';
import { getKPIs } from '../services/analyticsService';

const Modal = ({ isOpen, onClose, title, children }) => (
  <AnimatePresence>
    {isOpen && (
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, scale: 0.95 }}
          className="bg-white dark:bg-slate-900 rounded-3xl shadow-2xl w-full max-w-lg overflow-hidden"
        >
          <div className="flex items-center justify-between p-6 border-b dark:border-slate-800">
            <h3 className="text-xl font-bold">{title}</h3>
            <button onClick={onClose} className="p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-xl transition-colors">
              <X className="w-5 h-5" />
            </button>
          </div>
          <div className="p-6">{children}</div>
        </motion.div>
      </div>
    )}
  </AnimatePresence>
);

const AIInsights = () => {
  const [kpis, setKpis] = useState(null);
  const [loading, setLoading] = useState(true);
  const [refining, setRefining] = useState(false);
  const [activeModal, setActiveModal] = useState(null);

  useEffect(() => {
    const fetchKpis = async () => {
      try {
        const data = await getKPIs();
        setKpis(data);
      } catch (error) {
        console.error("Error fetching KPIs for AI insights:", error);
      } finally {
        setLoading(false);
      }
    };
    fetchKpis();
  }, []);

  if (loading) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-20">
        <Loader2 className="w-12 h-12 text-brand-600 animate-spin mb-4" />
        <p className="text-slate-500 font-medium">Analyzing business metrics...</p>
      </div>
    );
  }

  const hasData = kpis && kpis.totalRevenue > 0;

  const handleAction = (action) => {
    if (action === 'Refine Analysis') {
      setRefining(true);
      setTimeout(() => {
        setRefining(false);
        alert("Analysis refined based on latest market trends and seasonality factors.");
      }, 2000);
      return;
    }

    if (action === 'Download AI Report') {
      const reportContent = `
# SalesBI Executive AI Report
Date: ${new Date().toLocaleDateString()}

## Executive Summary
Total Revenue: $${(kpis.totalRevenue).toLocaleString()}
Profit Margin: ${kpis.profitMargin}%
Top Performing Region: ${kpis.topRegion}
Anchor Product: ${kpis.topProduct}

## Strategic Recommendations
1. Expansion: Increase marketing budget in ${kpis.topRegion} by 15% to leverage existing momentum.
2. Product Strategy: Create a "Starter Bundle" featuring ${kpis.topProduct} to drive cross-sales.
3. Operations: Review vendor contracts to improve the current ${kpis.profitMargin}% margin.

Generated by SalesBI AI Engine.
      `;
      const blob = new Blob([reportContent], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `SalesBI_AI_Report_${new Date().toISOString().split('T')[0]}.md`;
      link.click();
      return;
    }

    setActiveModal(action);
  };

  const insights = hasData ? [
    {
      type: 'performance',
      icon: TrendingUp,
      title: 'Regional Market Analysis',
      content: `Your highest performing region is ${kpis.topRegion}. Focus your marketing efforts here to capitalize on existing momentum.`,
      color: 'text-blue-600 bg-blue-50',
      action: 'Expand regional campaign'
    },
    {
      type: 'product',
      icon: Lightbulb,
      title: 'Product Popularity Insight',
      content: `${kpis.topProduct} has emerged as your top-selling product. Consider bundling it with slower-moving items to increase overall inventory turnover.`,
      color: 'text-emerald-600 bg-emerald-50',
      action: 'Create product bundle'
    },
    {
      type: 'efficiency',
      icon: Zap,
      title: 'Profitability Milestone',
      content: `You have achieved a profit margin of ${kpis.profitMargin}%. This indicates healthy operational efficiency relative to your total revenue of $${(kpis.totalRevenue/1000).toFixed(1)}k.`,
      color: 'text-brand-600 bg-brand-50',
      action: 'Review margin targets'
    }
  ] : [];

  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      <div className="text-center space-y-4">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand-100 text-brand-600 text-sm font-bold">
          <Zap className="w-4 h-4 fill-current" /> POWERED BY AI
        </div>
        <h2 className="text-4xl font-extrabold tracking-tight">Intelligent Business Insights</h2>
        <p className="text-slate-500 text-lg">Our AI engine analyzes your uploaded data to provide actionable recommendations.</p>
      </div>

      {!hasData ? (
        <div className="p-12 text-center glass rounded-3xl border-dashed border-2 border-slate-200">
          <Zap className="w-12 h-12 text-slate-300 mx-auto mb-4" />
          <h3 className="text-xl font-bold text-slate-400">No Data for Analysis</h3>
          <p className="text-slate-500 max-w-md mx-auto mt-2">
            Upload your sales records in the "Upload Dataset" tab. Once data is available, our AI will generate personalized business insights for you.
          </p>
        </div>
      ) : (
        <>
          <div className="grid gap-6">
            {insights.map((insight, index) => (
              <motion.div 
                key={index}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: index * 0.1 }}
                className="p-8 rounded-3xl glass flex flex-col md:flex-row gap-6 items-start"
              >
                <div className={`p-4 rounded-2xl ${insight.color}`}>
                  <insight.icon className="w-8 h-8" />
                </div>
                <div className="flex-1 space-y-4">
                  <div className="flex items-center justify-between">
                    <h3 className="text-xl font-bold">{insight.title}</h3>
                    <span className="text-xs font-bold uppercase tracking-widest text-slate-400">{insight.type}</span>
                  </div>
                  <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-lg">
                    {insight.content}
                  </p>
                  <button 
                    onClick={() => handleAction(insight.action)}
                    className="flex items-center gap-2 text-brand-600 font-bold group"
                  >
                    {insight.action} <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                  </button>
                </div>
              </motion.div>
            ))}
          </div>

          {/* Summary Section */}
          <div className="p-8 rounded-3xl bg-slate-900 text-white space-y-6">
            <h3 className="text-2xl font-bold">AI Executive Summary</h3>
            <p className="text-slate-400 leading-relaxed">
              Based on the processed dataset, your business is currently showing active performance in the **{kpis.topRegion}** market. 
              The total revenue of **${(kpis.totalRevenue/1000).toFixed(1)}k** with a **{kpis.profitMargin}%** profit margin suggests a stable foundation. 
              Focusing on **{kpis.topProduct}** as your anchor product could further drive growth in the next quarter.
            </p>
            <div className="flex gap-4">
              <button 
                onClick={() => handleAction('Download AI Report')}
                className="flex items-center gap-2 px-6 py-2 bg-white/10 rounded-xl text-sm font-bold hover:bg-white/20 transition-all"
              >
                <Download className="w-4 h-4" />
                Download Full AI Report
              </button>
              <button 
                onClick={() => handleAction('Refine Analysis')}
                disabled={refining}
                className="flex items-center gap-2 px-6 py-2 bg-brand-600 rounded-xl text-sm font-bold hover:bg-brand-700 transition-all disabled:opacity-50"
              >
                {refining ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCcw className="w-4 h-4" />}
                {refining ? 'Refining...' : 'Refine Analysis'}
              </button>
            </div>
          </div>
        </>
      )}

      {/* Modals for actions */}
      <Modal 
        isOpen={activeModal === 'Expand regional campaign'} 
        onClose={() => setActiveModal(null)}
        title="Regional Campaign Planner"
      >
        <div className="space-y-4">
          <p className="text-slate-600 dark:text-slate-400">Strategizing expansion for <span className="font-bold text-slate-900 dark:text-white">{kpis?.topRegion}</span>.</p>
          <div className="p-4 bg-slate-50 dark:bg-slate-800 rounded-2xl border dark:border-slate-700">
            <h4 className="font-bold mb-2">Recommended Channels:</h4>
            <ul className="text-sm space-y-2 text-slate-600 dark:text-slate-400">
              <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-emerald-500" /> Targeted Social Media (FB/IG)</li>
              <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-emerald-500" /> Local Search Optimization (SEO)</li>
              <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-emerald-500" /> Email Marketing for Existing Leads</li>
            </ul>
          </div>
          <button onClick={() => setActiveModal(null)} className="w-full py-3 bg-brand-600 text-white rounded-2xl font-bold">Launch Campaign</button>
        </div>
      </Modal>

      <Modal 
        isOpen={activeModal === 'Create product bundle'} 
        onClose={() => setActiveModal(null)}
        title="Product Bundle Creator"
      >
        <div className="space-y-4">
          <p className="text-slate-600 dark:text-slate-400">Creating a bundle for <span className="font-bold text-slate-900 dark:text-white">{kpis?.topProduct}</span>.</p>
          <div className="space-y-3">
            <div className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-800 rounded-xl">
              <span className="font-medium">{kpis?.topProduct}</span>
              <span className="text-brand-600 font-bold">Main Item</span>
            </div>
            <div className="text-center text-slate-400 font-bold">+</div>
            <select className="w-full p-3 bg-slate-50 dark:bg-slate-800 border dark:border-slate-700 rounded-xl outline-none">
              <option>Select companion product...</option>
              <option>Standard Shipping Warranty</option>
              <option>Premium Support Package</option>
              <option>Accessory Kit (Universal)</option>
            </select>
          </div>
          <button onClick={() => setActiveModal(null)} className="w-full py-3 bg-brand-600 text-white rounded-2xl font-bold">Save Bundle Strategy</button>
        </div>
      </Modal>

      <Modal 
        isOpen={activeModal === 'Review margin targets'} 
        onClose={() => setActiveModal(null)}
        title="Profit Margin Review"
      >
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <span className="text-slate-500">Current Margin</span>
            <span className="text-2xl font-black text-brand-600">{kpis?.profitMargin}%</span>
          </div>
          <div className="h-2 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
            <div className="h-full bg-brand-500" style={{ width: `${kpis?.profitMargin}%` }}></div>
          </div>
          <div className="p-4 bg-amber-50 dark:bg-amber-900/10 border border-amber-200 dark:border-amber-900/30 rounded-2xl">
            <p className="text-sm text-amber-700 dark:text-amber-500 font-medium">
              AI Suggestion: Increasing margins by 3% in the next quarter is possible by optimizing logistics in the West India region.
            </p>
          </div>
          <button onClick={() => setActiveModal(null)} className="w-full py-3 bg-slate-900 text-white rounded-2xl font-bold">Apply Optimization</button>
        </div>
      </Modal>
    </div>
  );
};

export default AIInsights;


